apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: kube-service2-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-service2
  minReplicas: 2
  maxReplicas: 4
  # targetCPUUtilizationPercentage: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50